### ISSUE TITLE
Login routes to uphold's 404 page

### ISSUE THREAD

**Issue by alexhidalgo** [uphold/uphold-sdk-android#110]
Tapping on the login button in the uphold sample app opens chrome and then ends up on a 404 page.

Uphold's website 404's when trying to reach this url https://uphold.com/authorize/e67a4ca1f3654e9cc0c530a717d1ada1e89a61fe?scope=cards:read%20user:read&state=4ikd1ceuho61qhqnu9n9qglnkr

**Comment by alexhidalgo** [comment]
![Screen Shot 2019-05-10 at 3 20 54 PM](https://user-images.githubusercontent.com/5232184/57559554-3e78a400-7337-11e9-910b-d8dfb7f7c30c.png)
![Screen Shot 2019-05-10 at 3 21 19 PM](https://user-images.githubusercontent.com/5232184/57559564-4e908380-7337-11e9-9642-546c3ad76ea1.png)

**Comment by SandroMachado** [comment]
Hi @alexhidalgo,

the app that you are trying to use is only registered on our sandbox environment, thats why it generates a 404 error when you try to access to that app in our production environment. 

Please let me know if you have any more doubts.
