### ISSUE TITLE
How to get the current balance using Android SDK

### ISSUE THREAD

**Issue by bh1r123** [uphold/uphold-sdk-android#62]
Hi There,

I have used the below method to get the current balnce but it's not working for all Can you help me how to get the correct value.

This is my current Implementation 
    user.getBalances().then(new PromiseAction<List<Currency>>() {
							@Override
							public void call(List<Currency> currencies) {
								Currency currency = currencies.get(0);
								Spanned fromHtml = Html.fromHtml(currency.getAmount()
										+ "<small> USD</small>");
								amount_display.setText(fromHtml);
								cancelLoader();
							}
						}).fail(new PromiseAction<Exception>() {
							@Override
							public void call(Exception e) {
								displayMessage("Exception is " + e.getMessage());
								cancelLoader();
							}
						});

**Comment by SandroMachado** [comment]
Hi @bh1r123, 

can you please provide me more details about the issue you are having? Do you get any exception?

To get the user balances you can do the following:

```Java
UpholdClient upholdClient = new UpholdClient(bearerToken);

upholdClient.getUser().then(new RepromiseFunction<User, UserBalance>() {
    @Override
    public Promise<UserBalance> call(User user) {
        Toast.makeText(UserActivity.this, user.getName(), Toast.LENGTH_LONG).show();

        return user.getTotalBalances();
    }
}).then(new PromiseAction<UserBalance>() {
    @Override
    public void call(UserBalance balance) {
        Toast.makeText(UserActivity.this, balance.getTotal(), Toast.LENGTH_LONG).show();
    }
}).fail(new PromiseAction<Exception>() {
    @Override
    public void call(Exception e) {
        Log.d(UserActivity.class.toString(), e.getMessage());
    }
});  
```

If you already have the `User` object you can just call `getTotalBalances()`:
```Java
user.getTotalBalances().then(new PromiseAction<UserBalance>() {
    @Override
    public void call(UserBalance userBalance) {
        Toast.makeText(UserActivity.this, userBalance.getTotal(), Toast.LENGTH_LONG).show();
    }
}).fail(new PromiseAction<Exception>() {
    @Override
    public void call(Exception e) {
        Log.d(UserActivity.class.toString(), e.getMessage());
    }
});
```

Please let me know if this helps.
