### ISSUE TITLE
User.getUserTransactions().hasNext throws an exception 

### ISSUE THREAD

**Issue by jsanchis** [uphold/uphold-sdk-android#85]
Hello, 

When paginator.hasNext().then(new PromiseAction<Boolean>() {... method is instantiated, having this paginator as User.getUserTransactions(), the request always fails because of an exception related with a null Integer value. This exception is thrown by the [line 464 of model.User](https://github.com/uphold/uphold-sdk-android/blob/master/src/app/src/main/java/com/uphold/uphold_android_sdk/model/User.java#L464):

`return (currentPage * Paginator.DEFAULT_OFFSET) < totalNumberOfResults;`

If I'm not wrong the issue is related with util.Header.getTotalNumberOfResults method when comparing the header name with "Content-Range", since the server's response has a header name "content-range".

So, at [util.Header.getTotalNumberOfResults, line 106](https://github.com/uphold/uphold-sdk-android/blob/master/src/app/src/main/java/com/uphold/uphold_android_sdk/util/Header.java#L106) we have:

`if (header.getName().compareTo("Content-Range") == 0) {
`
In my opinion, it should be:

`if (header.getName().toLowerCase().compareTo("Content-Range".toLowerCase()) == 0) {
`
or even better:

`if (header.getName().toLowerCase().compareTo("content-range") == 0) {
`

Thanks for your code,
Pepe Sanchis.

**Comment by SandroMachado** [comment]
Hi @jsanchis,

thanks for the details provided, I made a [PR](#85) to improve the `headers` comparison. The PR should  fix the issue.

Regards

**Comment by jsanchis** [comment]
Hi @SandroMachado ,

Indeed your change is much more elegant. 

Should I close the issue or do we wait until your PR is accepted?.

Regards,
Pepe.

**Comment by SandroMachado** [comment]
Hi @jsanchis,

I would prefer wait for the PR to be merged. It should be closed automatically due to the PR comment (`Closes #XX`).

Thanks again for your help.

Regards

**Comment by SandroMachado** [comment]
Hi @jsanchis,

the issue should be fixed at the new release [0.2.1](https://github.com/uphold/uphold-sdk-android/releases/tag/0.2.1).

Thanks for your help.

Regards
